#hardware params
gpus : 1
num_workers : 2

#network params
model_name: 'blazenet'
#video_resize_format: [128,128] #blazenet
video_resize_format: [128,128] #[224,224] #resnet18

vocab_size: 27
batch: 4
n_dimention : 500

#training params
lr : 0.00002
max_epoch : 100
save_prefix : "checkpoint"
save_every : 32
short_train : False

#loader params
video_dir: "/code/datasets/eLipSys/data/s1"
label_dir: "/code/datasets/eLipSys/data/alignments/s1"
max_frames_per_video: 75